; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103VC]
platform = ststm32
board = genericSTM32F103VC
framework = arduino

lib_deps =
    bodmer/TFT_eSPI

    adafruit/Adafruit GFX Library @ ^1.11.9
    adafruit/Adafruit BusIO @ ^1.16.1
    adafruit/Adafruit ILI9341 @ ^1.6.1
    greiman/SdFat @ ^2.2.2
    SPI
    Wire
    

build_flags = 
 -D USER_SETUP_LOADED=1
  -D ST7735_DRIVER=1
  -D TFT_WIDTH=160
  -D TFT_HEIGHT=128
  -D TFT_PARALLEL_8_BIT=1
  -D SPI_DRIVER_SELECT=2

  ; 修正後の制御信号
  -D TFT_CS=PD7
  -D TFT_RST=PE1
  -D TFT_WR=PD5
  -D TFT_RD=PD4
  -D TFT_DC=PD11    

  ; データバス 
  -D TFT_D0=PD14
  -D TFT_D1=PD15
  -D TFT_D2=PD0
  -D TFT_D3=PD1
  -D TFT_D4=PE7
  -D TFT_D5=PE8
  -D TFT_D6=PE9
  -D TFT_D7=PE10

  ; SPI関連のコードを完全に無効化するためのダミー
  -D STM32=1

  ; 書き込みエラー回避のための追加設定
upload_protocol = stlink
upload_flags = -c set CPUTAPID 0x2ba01477
monitor_speed = 115200